export const TRANSLATIONS = {
  de: {
    title: "Antragsverwaltung",
    subtitle:
      "Verwalte deine Anträge, lade Dateien hoch und behalte Fristen im Blick – alles an einem zentralen Ort.",
    search: "Anträge durchsuchen...",
    allStatus: "Alle Status",
    pending: "In Bearbeitung",
    approved: "Genehmigt",
    rejected: "Abgelehnt",
    allCategories: "Alle Kategorien",
    totalApplications: "Gesamt",
    pendingCount: "In Bearbeitung",
    approvedCount: "Genehmigt",
    rejectedCount: "Abgelehnt",
    lastUpdated: "Zuletzt aktualisiert",
    startApplication: "Bearbeiten",
    moreInfo: "Details",
    noResults: "Keine Anträge gefunden",
    noResultsHint: "Versuchen Sie andere Suchbegriffe oder Filter",
    submitApplication: "Antrag abschließen",
    cancel: "Abbrechen",
    submitting: "Wird verarbeitet...",
    requiredField: "Pflichtfeld",
    uploadFile: "Datei hochladen",
    successMessage: "Antrag erfolgreich aktualisiert!",
    task: "Antragsverwaltung",
    categories: {
      examOffice: "Prüfungsamt",
      studentOffice: "Studierendensekretariat",
    },
    itemTitles: {
      "1": "Anmeldung zur Abschlussarbeit Erst- und Zweitversuch",
      "2": "Nachteilsausgleich prüfen",
      "3": "Verlängerung der Bearbeitungszeit",
      "4": "Beurlaubung einreichen",
      "5": "Online Einsicht anfordern",
      "6": "Online Einwand einlegen",
      "7": "Upload Bescheinigung der Prüfungsunfähigkeit",
      "8": "Anmeldung zur Abschlussarbeit - Erstversuch",
      "9": "Anmeldung zur Abschlussarbeit - Zweitversuch",
      "10": "Verlängerung der Bearbeitungszeit (VFS)",
      "11": "Zulassung zum Kolloquium",
      "12": "Campuswechsel beantragen",
      "13": "Kostenlose Online-Weiterbildung (ab 3. Sem.)",
      "14": "Studiengangswechsel prüfen",
      "15": "Vorzeitige Exmatrikulation (Ende 7. Sem.)",
      "16": "Vertragsverlängerung ins 8. Semester",
      "17": "Vertiefungswechsel einreichen",
    },
  },
  en: {
    title: "Application Management",
    subtitle:
      "Manage your applications, upload files and keep track of deadlines – all in one central place.",
    search: "Search applications...",
    allStatus: "All Status",
    pending: "In Progress",
    approved: "Approved",
    rejected: "Rejected",
    allCategories: "All Categories",
    totalApplications: "Total",
    pendingCount: "In Progress",
    approvedCount: "Approved",
    rejectedCount: "Rejected",
    lastUpdated: "Last updated",
    startApplication: "Edit",
    moreInfo: "Details",
    noResults: "No applications found",
    noResultsHint: "Try different search terms or filters",
    submitApplication: "Complete Application",
    cancel: "Cancel",
    submitting: "Processing...",
    requiredField: "Required field",
    uploadFile: "Upload file",
    successMessage: "Application updated successfully!",
    task: "Application Management",
    categories: {
      examOffice: "Examination Office",
      studentOffice: "Student Office",
    },
    itemTitles: {
      "1": "Registration for Thesis First and Second Attempt",
      "2": "Check disadvantage compensation",
      "3": "Extension of processing time",
      "4": "Submit leave of absence",
      "5": "Request online inspection",
      "6": "File online objection",
      "7": "Upload certificate of incapacity for examination",
      "8": "Registration for Thesis - First Attempt",
      "9": "Registration for Thesis - Second Attempt",
      "10": "Extension of processing time (VFS)",
      "11": "Admission to colloquium",
      "12": "Apply for campus change",
      "13": "Free online further education (from 3rd sem.)",
      "14": "Check change of study program",
      "15": "Early exmatriculation (end of 7th sem.)",
      "16": "Contract extension into 8th semester",
      "17": "Submit change of specialization",
    },
  },
};

export const getFormDefinitions = (t: any) => ({
  "1": {
    title: t.itemTitles["1"],
    fields: [
      {
        name: "studentName",
        label: t.task === "Task" ? "Name" : "Name",
        type: "text",
        required: true,
      },
      {
        name: "matrikelNummer",
        label: t.task === "Task" ? "Matriculation Number" : "Matrikelnummer",
        type: "text",
        required: true,
      },
      {
        name: "thesisTitle",
        label: t.task === "Task" ? "Thesis Title" : "Titel der Abschlussarbeit",
        type: "text",
        required: true,
      },
      {
        name: "supervisor",
        label: t.task === "Task" ? "Supervisor" : "Betreuer",
        type: "text",
        required: true,
      },
      {
        name: "company",
        label: t.task === "Task" ? "Company" : "Unternehmen",
        type: "text",
        required: false,
      },
      {
        name: "startDate",
        label:
          t.task === "Task" ? "Desired Start Date" : "Gewünschtes Startdatum",
        type: "date",
        required: true,
      },
      {
        name: "documents",
        label: t.task === "Task" ? "Upload Documents" : "Dokumente hochladen",
        type: "file",
        required: false,
      },
    ],
    microsoftFormUrl: "https://forms.office.com/e/z0xk9ttuJY",
  },
  "2": {
    title: t.itemTitles["2"],
    fields: [
      {
        name: "studentName",
        label: t.task === "Task" ? "Name" : "Name",
        type: "text",
        required: true,
      },
      {
        name: "matrikelNummer",
        label: t.task === "Task" ? "Matriculation Number" : "Matrikelnummer",
        type: "text",
        required: true,
      },
      {
        name: "disability",
        label:
          t.task === "Task" ? "Type of impairment" : "Art der Beeinträchtigung",
        type: "textarea",
        required: true,
      },
      {
        name: "requestedAccommodation",
        label:
          t.task === "Task" ? "Requested measures" : "Beantragte Maßnahmen",
        type: "textarea",
        required: true,
      },
      {
        name: "medicalCertificate",
        label: t.task === "Task" ? "Medical certificate" : "Ärztliches Attest",
        type: "file",
        required: true,
      },
    ],
    microsoftFormUrl:
      "https://forms.office.com/Pages/ResponsePage.aspx?id=YOUR_FORM_ID_2",
  },
  "3": {
    title: t.itemTitles["3"],
    fields: [
      {
        name: "studentName",
        label: t.task === "Task" ? "Name" : "Name",
        type: "text",
        required: true,
      },
      {
        name: "matrikelNummer",
        label: t.task === "Task" ? "Matriculation Number" : "Matrikelnummer",
        type: "text",
        required: true,
      },
      {
        name: "currentDeadline",
        label: t.task === "Task" ? "Current deadline" : "Aktuelle Frist",
        type: "date",
        required: true,
      },
      {
        name: "requestedExtension",
        label:
          t.task === "Task"
            ? "Requested extension (weeks)"
            : "Beantragte Verlängerung (Wochen)",
        type: "number",
        required: true,
      },
      {
        name: "reason",
        label: t.task === "Task" ? "Reason" : "Begründung",
        type: "textarea",
        required: true,
      },
      {
        name: "supportingDocuments",
        label: t.task === "Task" ? "Supporting documents" : "Nachweise",
        type: "file",
        required: false,
      },
    ],
    microsoftFormUrl:
      "https://forms.office.com/Pages/ResponsePage.aspx?id=YOUR_FORM_ID_3",
  },
  default: {
    title: t.task === "Task" ? "General Application" : "Allgemeiner Antrag",
    fields: [
      {
        name: "studentName",
        label: t.task === "Task" ? "Name" : "Name",
        type: "text",
        required: true,
      },
      {
        name: "matrikelNummer",
        label: t.task === "Task" ? "Matriculation Number" : "Matrikelnummer",
        type: "text",
        required: true,
      },
      {
        name: "requestDetails",
        label: t.task === "Task" ? "Request details" : "Details des Antrags",
        type: "textarea",
        required: true,
      },
      {
        name: "documents",
        label: t.task === "Task" ? "Documents" : "Dokumente",
        type: "file",
        required: false,
      },
    ],
    microsoftFormUrl: null,
  },
});

export const MOCK_ITEMS = [
  {
    id: "1",
    titleKey: "1",
    status: "pending",
    updatedAt: new Date().toISOString(),
    info: true,
    categoryKey: "examOffice",
  },
  {
    id: "2",
    titleKey: "2",
    status: "pending",
    updatedAt: new Date().toISOString(),
    categoryKey: "examOffice",
  },
  {
    id: "3",
    titleKey: "3",
    status: "approved",
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    info: true,
    categoryKey: "examOffice",
  },
  {
    id: "4",
    titleKey: "4",
    status: "pending",
    updatedAt: new Date().toISOString(),
    info: true,
    categoryKey: "examOffice",
  },
  {
    id: "5",
    titleKey: "5",
    status: "pending",
    updatedAt: new Date().toISOString(),
    categoryKey: "examOffice",
  },
  {
    id: "6",
    titleKey: "6",
    status: "rejected",
    updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    categoryKey: "examOffice",
  },
  {
    id: "7",
    titleKey: "7",
    status: "pending",
    updatedAt: new Date().toISOString(),
    info: true,
    categoryKey: "examOffice",
  },
  {
    id: "8",
    titleKey: "8",
    status: "pending",
    updatedAt: new Date().toISOString(),
    info: true,
    categoryKey: "examOffice",
  },
  {
    id: "9",
    titleKey: "9",
    status: "pending",
    updatedAt: new Date().toISOString(),
    info: true,
    categoryKey: "examOffice",
  },
  {
    id: "10",
    titleKey: "10",
    status: "approved",
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    info: true,
    categoryKey: "examOffice",
  },
  {
    id: "11",
    titleKey: "11",
    status: "pending",
    updatedAt: new Date().toISOString(),
    categoryKey: "examOffice",
  },
  {
    id: "12",
    titleKey: "12",
    status: "pending",
    updatedAt: new Date().toISOString(),
    info: true,
    categoryKey: "studentOffice",
  },
  {
    id: "13",
    titleKey: "13",
    status: "pending",
    updatedAt: new Date().toISOString(),
    info: true,
    categoryKey: "studentOffice",
  },
  {
    id: "14",
    titleKey: "14",
    status: "pending",
    updatedAt: new Date().toISOString(),
    info: true,
    categoryKey: "studentOffice",
  },
  {
    id: "15",
    titleKey: "15",
    status: "pending",
    updatedAt: new Date().toISOString(),
    categoryKey: "studentOffice",
  },
  {
    id: "16",
    titleKey: "16",
    status: "approved",
    updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    categoryKey: "studentOffice",
  },
  {
    id: "17",
    titleKey: "17",
    status: "pending",
    updatedAt: new Date().toISOString(),
    categoryKey: "studentOffice",
  },
];
