export const TRANSLATIONS = {
  de: {
    back: "Zurück zum Dashboard",
    title: "Support & Kontakt",
    subtitle:
      "Wir helfen dir gerne bei Fragen und Problemen. Unser Team steht dir zur Verfügung.",
    available: "Support verfügbar",
    writeUs: "Schreib uns eine Nachricht",
    autoAttach:
      "Deine IU-Anmeldedaten (Name & E-Mail) hängen wir automatisch an.",
    responseTime: "Durchschn. Antwortzeit: 1h",
    sentTitle: "Nachricht gesendet!",
    sentBody: "Wir melden uns schnellstmöglich bei dir.",
    subject: "Betreff",
    subjectPlaceholder: "-- Wähle ein Thema --",
    subjectOptions: {
      studienplan: "Studienplan",
      klausuren: "Klausuren",
      raumbuchung: "Raumbuchung",
      dateien: "Dateien & Materialien",
      technisch: "Technische Probleme",
      sonstiges: "Sonstiges",
    },
    message: "Nachricht",
    messagePlaceholder: "Beschreibe dein Anliegen ausführlich...",
    sending: "Wird gesendet...",
    send: "Nachricht senden",
    errorGeneric: "Fehler beim Senden der Nachricht",
    errorNetwork: "Netzwerkfehler. Bitte versuche es später erneut.",
    supportHours: "Support-Zeiten",
    monFri: "Montag - Freitag",
    sat: "Samstag",
    sun: "Sonntag",
    closed: "Geschlossen",
    emergency: "Notfall-Hotline",
    emergencyDesc: "Bitte nur bei technischen Notfällen nutzen",
    chatTitle: "Chat & Self-Service",
    chatDesc: "Schnelle Antworten über unseren Chatbot und das FAQ.",
    resourcesTitle: "Beliebte Ressourcen",
    studentId: "Studentenausweis",
    modules: "Module & Fächer",
    handbook: "Modulhandbuch",
    toolsTitle: "Tools & Services",
    housing: "Housing",
    praxis: "Praxisberichte",
    portal: "Bibliothek / Portale",
  },
  en: {
    back: "Back to dashboard",
    title: "Support & Contact",
    subtitle:
      "We're here to help with questions or issues. Our team is available for you.",
    available: "Support available",
    writeUs: "Send us a message",
    autoAttach:
      "We'll attach your IU account data (name & email) automatically.",
    responseTime: "Avg. response time: 1h",
    sentTitle: "Message sent!",
    sentBody: "We'll get back to you as soon as possible.",
    subject: "Subject",
    subjectPlaceholder: "-- Choose a topic --",
    subjectOptions: {
      studienplan: "Study plan",
      klausuren: "Exams",
      raumbuchung: "Room booking",
      dateien: "Files & materials",
      technisch: "Technical issues",
      sonstiges: "Other",
    },
    message: "Message",
    messagePlaceholder: "Describe your issue in detail...",
    sending: "Sending...",
    send: "Send message",
    errorGeneric: "Failed to send message",
    errorNetwork: "Network error. Please try again later.",
    supportHours: "Support hours",
    monFri: "Monday - Friday",
    sat: "Saturday",
    sun: "Sunday",
    closed: "Closed",
    emergency: "Emergency hotline",
    emergencyDesc: "Use only for technical emergencies",
    chatTitle: "Chat & self-service",
    chatDesc: "Get quick answers via chatbot and FAQ.",
    resourcesTitle: "Popular resources",
    studentId: "Student ID",
    modules: "Modules & subjects",
    handbook: "Module handbook",
    toolsTitle: "Tools & services",
    housing: "Housing",
    praxis: "Practical reports",
    portal: "Library / portals",
  },
};
