import {
  Building2,
  Home,
  Briefcase,
  Laptop,
  Users,
  Heart,
  Plane,
  Globe,
  TrendingUp,
  Palette,
} from "lucide-react";

export const TRANSLATIONS = {
  de: {
    back: "Zurück zur Studienorganisation",
    title: "Zusatzkurs wählen",
    subtitle: "Wählen Sie einen Weiterbildungskurs aus dem Angebot der IU",
    howItWorks: "So funktioniert es",
    step1: "Kurs auswählen: Wählen Sie einen Weiterbildungskurs aus",
    step2:
      'Zu den Abgaben: Dort finden Sie den Antrag "Kostenlose Online-Weiterbildung"',
    step3:
      "Antrag ausfüllen: Tragen Sie den ausgewählten Kurs in das Formular ein",
    importantNote: "Wichtiger Hinweis",
    noteText:
      "Pro Antrag kann nur ein Zusatzkurs beantragt werden. Wenn Sie mehrere Kurse belegen möchten, müssen Sie für jeden Kurs einen separaten Antrag in den Abgaben stellen.",
    searchPlaceholder: "Kurs suchen...",
    allCategories: "Alle Kategorien",
    selectedCourse: "Ausgewählter Kurs",
    noCourseSelected: "Noch kein Kurs ausgewählt",
    selectCourseHint: "Wählen Sie einen Kurs aus dem Katalog aus",
    yourData: "Ihre Daten",
    firstName: "Vorname",
    lastName: "Nachname",
    matriculation: "Matrikel-Nr.",
    program: "Studiengang",
    semester: "Semester",
    summary: "Zusammenfassung",
    courseCount: "Anzahl Kurse",
    credits: "Credits",
    goToApplication: "Zur Antragsverwaltung",
    courses: "Kurse",
    noCourses: "Keine Kurse gefunden",
  },
  en: {
    back: "Back to Study Organization",
    title: "Select Additional Course",
    subtitle: "Choose a continuing education course from IU's offerings",
    howItWorks: "How it works",
    step1: "Select a course: Choose one continuing education course",
    step2:
      'Go to Application Management: Find the "Free Online Continuing Education" application there',
    step3: "Fill out the application: Enter the selected course in the form",
    importantNote: "Important Notice",
    noteText:
      "Only one additional course can be requested per application. If you want to take multiple courses, you must submit a separate application for each course in the Application Management.",
    searchPlaceholder: "Search course...",
    allCategories: "All Categories",
    selectedCourse: "Selected Course",
    noCourseSelected: "No course selected yet",
    selectCourseHint: "Select a course from the catalog",
    yourData: "Your Data",
    firstName: "First Name",
    lastName: "Last Name",
    matriculation: "Matriculation No.",
    program: "Study Program",
    semester: "Semester",
    summary: "Summary",
    courseCount: "Number of Courses",
    credits: "Credits",
    goToApplication: "Go to Application Management",
    courses: "Courses",
    noCourses: "No courses found",
  },
};

export const STUDENT_DATA = {
  vorname: "Sabin",
  nachname: "El Anwar",
  matrikelnummer: "102203036",
  studiengang: "Wirtschaftsinformatik (B.Sc.)",
  semester: 6,
};

export const ZUSATZKURSE_CATEGORIES = [
  {
    id: "architektur",
    name: "Architektur",
    icon: Building2,
    color: "slate",
    description: "Zusätzliche Kompetenzen im Bereich Architektur und Design",
    courses: [
      {
        id: "arch-001",
        name: "Darstellen: CAD",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "arch-002",
        name: "Darstellen: Modellbau",
        credits: 5,
        type: "Weiterbildung",
      },
    ],
  },
  {
    id: "bauingenieurwesen",
    name: "Bauingenieurwesen",
    icon: Home,
    color: "orange",
    description: "Technische Kenntnisse im Bauwesen",
    courses: [
      {
        id: "bau-001",
        name: "Gebäudetechnik",
        credits: 5,
        type: "Weiterbildung",
      },
    ],
  },
  {
    id: "bwl",
    name: "BWL",
    icon: Briefcase,
    color: "blue",
    description: "Betriebswirtschaftliche Zusatzqualifikationen",
    courses: [
      {
        id: "bwl-001",
        name: "Planen und Entscheiden",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "bwl-002",
        name: "Enterprise Resource Planning",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "bwl-003",
        name: "Unternehmensplanung und –kontrolle",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "bwl-004",
        name: "Business-Controlling I",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "bwl-005",
        name: "Business-Controlling II",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "bwl-006",
        name: "Financial Services Management I",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "bwl-007",
        name: "Financial Services Management II",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "bwl-008",
        name: "International Management",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "bwl-009",
        name: "Luftverkehrsmanagement",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "bwl-010",
        name: "Corporate Finance",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "bwl-011",
        name: "Finanzmanagement",
        credits: 5,
        type: "Weiterbildung",
      },
      { id: "bwl-012", name: "BWL I", credits: 5, type: "Weiterbildung" },
      { id: "bwl-013", name: "BWL II", credits: 5, type: "Weiterbildung" },
      {
        id: "bwl-014",
        name: "Unternehmensführung",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "bwl-015",
        name: "Unternehmensrecht",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "bwl-016",
        name: "Investition und Finanzierung",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "bwl-017",
        name: "Nachhaltigkeits- und Qualitätsmanagement",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "bwl-018",
        name: "Makroökonomie",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "bwl-019",
        name: "Mikroökonomie I",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "bwl-020",
        name: "Mikroökonomie II",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "bwl-021",
        name: "Ökonomie und Markt",
        credits: 5,
        type: "Weiterbildung",
      },
      { id: "bwl-022", name: "Statistik", credits: 5, type: "Weiterbildung" },
    ],
  },
  {
    id: "immobilienmanagement",
    name: "Immobilienmanagement",
    icon: Building2,
    color: "emerald",
    description: "Spezialisierung auf Immobilienwirtschaft",
    courses: [
      {
        id: "immo-001",
        name: "Angewandter Vertrieb I",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "immo-002",
        name: "Angewandter Vertrieb II",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "immo-003",
        name: "Negotiation I",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "immo-004",
        name: "Negotiation II",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "immo-005",
        name: "Immobilienrecht I",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "immo-006",
        name: "Immobilienrecht II",
        credits: 5,
        type: "Weiterbildung",
      },
    ],
  },
  {
    id: "it",
    name: "IT",
    icon: Laptop,
    color: "indigo",
    description: "Erweiterte IT-Kompetenzen und Spezialisierungen",
    courses: [
      {
        id: "it-001",
        name: "Grundlagen der industriellen Softwaretechnik",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "it-002",
        name: "Requirements Engineering",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "it-003",
        name: "Grundlagen der Softwaretechnik",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "it-004",
        name: "Einführung in Datenschutz und IT-Sicherheit",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "it-005",
        name: "Kryptografische Verfahren",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "it-006",
        name: "Mathematik Grundlagen I",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "it-007",
        name: "Mathematik Grundlagen II",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "it-008",
        name: "Automatisierung und Robotics",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "it-009",
        name: "Einführung in das Internet of Things",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "it-010",
        name: "Smart Devices",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "it-011",
        name: "Smart Mobility",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "it-012",
        name: "Smart Services",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "it-013",
        name: "Informatik und Gesellschaft",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "it-014",
        name: "Data Analytics und Big Data",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "it-015",
        name: "IT Project Management",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "it-016",
        name: "IT Architecture Management",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "it-017",
        name: "Artificial Intelligence",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "it-018",
        name: "Projekt: KI-Exzellenz mit kreativen Prompt-Techniken",
        credits: 5,
        type: "Weiterbildung",
        status: "passed",
        grade: "1,0",
      },
    ],
  },
  {
    id: "kindheitspaedagogik",
    name: "Kindheitspädagogik",
    icon: Users,
    color: "pink",
    description: "Pädagogische Zusatzqualifikationen",
    courses: [
      {
        id: "kp-001",
        name: "Interkulturelle Psychologie",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "kp-002",
        name: "Konfliktmanagement und Mediation",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "kp-003",
        name: "Psychologische Diagnostik",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "kp-004",
        name: "Social Entrepreneurship",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "kp-005",
        name: "Einführung in die Heilpädagogik",
        credits: 5,
        type: "Weiterbildung",
      },
    ],
  },
  {
    id: "kommunikation",
    name: "Kommunikation & PR",
    icon: Globe,
    color: "violet",
    description: "Kommunikationskompetenzen und Public Relations",
    courses: [
      {
        id: "kom-001",
        name: "Medienökonomie",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "kom-002",
        name: "Grundlagen Print- und Layoutsysteme",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "kom-003",
        name: "Kommunikation und Public Relations",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "kom-004",
        name: "Digital Skills",
        credits: 5,
        type: "Weiterbildung",
      },
    ],
  },
  {
    id: "marketing",
    name: "Marketingmanagement",
    icon: TrendingUp,
    color: "rose",
    description: "Marketing- und Vertriebskompetenzen",
    courses: [
      {
        id: "mark-001",
        name: "Globale Unternehmen und Globalisierung",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "mark-002",
        name: "Global Sourcing",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "mark-003",
        name: "Wirtschaftspsychologie",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "mark-004",
        name: "Online-Marketing",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "mark-005",
        name: "Social Media Marketing",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "mark-006",
        name: "E-Commerce I",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "mark-007",
        name: "E-Commerce II",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "mark-008",
        name: "Internationales Brand Management",
        credits: 5,
        type: "Weiterbildung",
      },
    ],
  },
  {
    id: "mediendesign",
    name: "Mediendesign",
    icon: Palette,
    color: "fuchsia",
    description: "Kreative und gestalterische Kompetenzen",
    courses: [
      {
        id: "med-001",
        name: "Customer Relationship Management",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "med-002",
        name: "Digitales Redaktionsmanagement",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "med-003",
        name: "Storytelling",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "med-004",
        name: "Corporate Communication",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "med-005",
        name: "Influencer Marketing",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "med-006",
        name: "Web-Analytics",
        credits: 5,
        type: "Weiterbildung",
      },
    ],
  },
  {
    id: "personal",
    name: "Personal",
    icon: Users,
    color: "cyan",
    description: "HR und Personalmanagement",
    courses: [
      {
        id: "pers-001",
        name: "Grundlagen der Arbeits- und Organisationspsychologie",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "pers-002",
        name: "Advanced Leadership I",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "pers-003",
        name: "Advanced Leadership II",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "pers-004",
        name: "Personalwesen Spezialisierung I",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "pers-005",
        name: "Agiles Management",
        credits: 5,
        type: "Weiterbildung",
      },
    ],
  },
  {
    id: "soziales",
    name: "Soziales & Gesundheit",
    icon: Heart,
    color: "red",
    description: "Gesundheits- und Sozialwesen",
    courses: [
      {
        id: "soz-001",
        name: "Interkulturelles Management",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "soz-002",
        name: "Sozialmanagement",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "soz-003",
        name: "Betriebliches Gesundheitsmanagement",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "soz-004",
        name: "Betriebspsychologie",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "soz-005",
        name: "Social Psychology",
        credits: 5,
        type: "Weiterbildung",
      },
    ],
  },
  {
    id: "tourismus",
    name: "Tourismus & Gastronomie",
    icon: Plane,
    color: "sky",
    description: "Event- und Tourismusmanagement",
    courses: [
      {
        id: "tour-001",
        name: "Kreuzfahrttourismus",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "tour-002",
        name: "Gastronomiemanagement",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "tour-003",
        name: "Sportevents",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "tour-004",
        name: "Messe- und Ausstellungsmanagement",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "tour-005",
        name: "Nachhaltigkeitsmanagement",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "tour-006",
        name: "Gesundheitstourismus",
        credits: 5,
        type: "Weiterbildung",
      },
    ],
  },
  {
    id: "sprachen",
    name: "Sprachkurse",
    icon: Globe,
    color: "teal",
    description: "Fremdsprachenkenntnisse erweitern",
    courses: [
      {
        id: "spr-001",
        name: "Fremdsprache Französisch",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "spr-002",
        name: "Fremdsprache Italienisch",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "spr-003",
        name: "Fremdsprache Spanisch",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "spr-004",
        name: "Fremdsprache Englisch",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "spr-005",
        name: "Gebärdensprache",
        credits: 5,
        type: "Weiterbildung",
      },
    ],
  },
  {
    id: "onlineklausur",
    name: "Online-Module",
    icon: Laptop,
    color: "purple",
    description: "Flexible Online-Weiterbildungen",
    courses: [
      {
        id: "onl-001",
        name: "Sozialwirtschaft",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "onl-002",
        name: "Computertraining",
        credits: 5,
        type: "Weiterbildung",
      },
      { id: "onl-003", name: "Marketing", credits: 5, type: "Weiterbildung" },
      { id: "onl-004", name: "Recht", credits: 5, type: "Weiterbildung" },
      {
        id: "onl-005",
        name: "Wirtschaftsmathematik",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "onl-006",
        name: "Projektmanagement",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "onl-007",
        name: "Digital Skills",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "onl-008",
        name: "Collaborative Work",
        credits: 5,
        type: "Weiterbildung",
      },
      {
        id: "onl-009",
        name: "Personal Skills",
        credits: 5,
        type: "Weiterbildung",
      },
    ],
  },
];
