import type {
  GradeStatusKey as StatusKey,
  GradeSection as Section,
} from "~/types/grades";

export const TRANSLATIONS = {
  de: {
    transcriptTitle: "Transcript & Notenverwaltung",
    universityName: "IU Internationale Hochschule",
    overallAverage: "Gesamtdurchschnitt",
    totalModules: "Module gesamt",
    passed: "Bestanden",
    openRegistered: "Offen/Angem.",
    failed: "Durchgefallen",
    searchPlaceholder: "Suchen (Modulname)…",
    allStatus: "Alle Status",
    statusPassed: "P — Bestanden",
    statusOpen: "M — Offen",
    statusRegistered: "CE — Angemeldet",
    statusExamRegistered: "E — Zur Prüfung angemeldet",
    statusFailed: "F — Nicht bestanden",
    sortNone: "Sortierung: Keine",
    sortDate: "Datum",
    sortGrade: "Note",
    expandAll: "Alle ausklappen",
    collapseAll: "Alle einklappen",
    exportPDF: "Export PDF",
    exportCSV: "Export CSV",
    performanceOverview: "Performance-Übersicht",
    passRate: "Passrate",
    noEntries: "Keine Einträge für diesen Filter.",
    legend: "Legende",
    module: "Modul",
    status: "Status",
    grade: "Note",
    credits: "Credits",
    date: "Datum",
    assessment: "Bewertung",
    section: "Sektion",
    generatedOn: "Generiert am",
    officialTranscript: "Official Transcript of Records",
    student: "Studierende*r",
    matriculationNumber: "Matrikelnummer",
    gradeExcellent: "Note ≤ 1.5 · sehr gut",
    gradeGood: "1.6–2.5 · gut",
    gradeSatisfactory: "2.6–3.5 · befriedigend",
    gradeSufficient: "≥ 3.6 · ausreichend / mangelhaft",
    chipLabels: {
      P: "Bestanden",
      F: "Nicht bestanden",
      M: "Offen",
      CE: "Angemeldet",
      E: "Zur Prüfung angemeldet",
    },
    tabOverview: "Erbrachte Leistungen",
    tabOpen: "Offene Leistungen",
    tabFailed: "Nicht bestandene Kurse",
    gradeDistribution: "Notenverteilung",
    recentGrades: "Neueste Noten",
    semesterProgress: "Semesterfortschritt",
    ectsProgress: "ECTS Fortschritt",
    averageTrend: "Notentrend",
    exportOptions: "Export-Optionen",
    filterAndSort: "Filter & Sortierung",
    noData: "Keine Daten verfügbar",
    excellent: "Ausgezeichnet",
    good: "Gut",
    satisfactory: "Befriedigend",
    sufficient: "Ausreichend",
    failed_short: "Nicht best.",
  },
  en: {
    transcriptTitle: "Transcript & Grade Management",
    universityName: "IU International University",
    overallAverage: "Overall Average",
    totalModules: "Total Modules",
    passed: "Passed",
    openRegistered: "Open/Reg.",
    failed: "Failed",
    searchPlaceholder: "Search (module name)…",
    allStatus: "All Status",
    statusPassed: "P — Passed",
    statusOpen: "M — Open",
    statusRegistered: "CE — Registered",
    statusExamRegistered: "E — Exam Registered",
    statusFailed: "F — Failed",
    sortNone: "Sort: None",
    sortDate: "Date",
    sortGrade: "Grade",
    expandAll: "Expand All",
    collapseAll: "Collapse All",
    exportPDF: "Export PDF",
    exportCSV: "Export CSV",
    performanceOverview: "Performance Overview",
    passRate: "Pass Rate",
    noEntries: "No entries for this filter.",
    legend: "Legend",
    module: "Module",
    status: "Status",
    grade: "Grade",
    credits: "Credits",
    date: "Date",
    assessment: "Assessment",
    section: "Section",
    generatedOn: "Generated on",
    officialTranscript: "Official Transcript of Records",
    student: "Student",
    matriculationNumber: "Matriculation Number",
    gradeExcellent: "Grade ≤ 1.5 · Excellent",
    gradeGood: "1.6–2.5 · Good",
    gradeSatisfactory: "2.6–3.5 · Satisfactory",
    gradeSufficient: "≥ 3.6 · Sufficient / Poor",
    chipLabels: {
      P: "Passed",
      F: "Failed",
      M: "Open",
      CE: "Registered",
      E: "Exam Registered",
    },
    tabOverview: "Academic Achievements",
    tabOpen: "Open Courses",
    tabFailed: "Failed Courses",
    gradeDistribution: "Grade Distribution",
    recentGrades: "Recent Grades",
    semesterProgress: "Semester Progress",
    ectsProgress: "ECTS Progress",
    averageTrend: "Grade Trend",
    exportOptions: "Export Options",
    filterAndSort: "Filter & Sort",
    noData: "No data available",
    excellent: "Excellent",
    good: "Good",
    satisfactory: "Satisfactory",
    sufficient: "Sufficient",
    failed_short: "Failed",
  },
};

export const STUDENT_DATA = {
  vorname: "Sabin",
  name: "El Anwar",
  matrikelnummer: "102203036",
  studiengang: "Wirtschaftsinformatik (HH-BA-WINFO-WiSe-22-GTW)",
  gesamtDurchschnitt: 1.58,
};

export const SEMESTERS: Section[] = [
  {
    name: "1. Semester",
    modules: [
      {
        name: "Grundlagen der BWL",
        status: "P",
        note: 1.3,
        credits: 5,
        datum: "31.03.2023",
      },
      {
        name: "Mathematik I",
        status: "P",
        note: 2.3,
        credits: 5,
        datum: "21.02.2023",
      },
      {
        name: "Industrielle Softwaretechnik (MP)",
        status: "P",
        note: 2.0,
        credits: 5,
        datum: "16.02.2023",
      },
      {
        name: "Wissenschaftliches Arbeiten",
        status: "P",
        note: 1.0,
        credits: 5,
        datum: "26.03.2023",
      },
      {
        name: "Praxisprojekt I",
        status: "P",
        note: 1.3,
        credits: 5,
        datum: "29.06.2023",
      },
    ],
  },
  {
    name: "2. Semester",
    modules: [
      {
        name: "Buchführung und Jahresabschluss",
        status: "P",
        note: 1.7,
        credits: 5,
        datum: "21.08.2023",
        bewertung: "90/100",
      },
      {
        name: "Mathematik Grundlagen II",
        status: "P",
        note: 4.0,
        credits: 5,
        datum: "25.08.2023",
        bewertung: "51.11/100",
      },
      {
        name: "Objektorientierte Programmierung I",
        status: "P",
        note: 2.7,
        credits: 5,
        datum: "18.08.2023",
        bewertung: "84.3/90",
      },
      {
        name: "Fallstudie Digitale Business Modelle",
        status: "P",
        note: 1.7,
        credits: 5,
        datum: "20.07.2023",
        bewertung: "89/100",
      },
      {
        name: "Praxisprojekt II",
        status: "P",
        note: 1.0,
        credits: 5,
        datum: "24.10.2023",
        bewertung: "100/100",
      },
    ],
  },
  {
    name: "3. Semester",
    modules: [
      {
        name: "Kosten- und Leistungsrechnung",
        status: "P",
        note: 1.3,
        credits: 5,
        datum: "06.02.2024",
        bewertung: "91.11/100",
      },
      {
        name: "Marketing",
        status: "P",
        note: 2.0,
        credits: 5,
        datum: "–",
        bewertung: "81/100",
      },
      {
        name: "Requirement Engineering (MP)",
        status: "P",
        note: 2.3,
        credits: 5,
        datum: "14.02.2024",
        bewertung: "70.5/90",
      },
      {
        name: "Praxisprojekt III",
        status: "P",
        note: 1.0,
        credits: 5,
        datum: "30.03.2024",
        bewertung: "86.4/80",
      },
      {
        name: "Objektorientierte Programmierung II",
        status: "P",
        note: 2.3,
        credits: 5,
        datum: "–",
        bewertung: "76/100",
      },
    ],
  },
  {
    name: "4. Semester",
    modules: [
      {
        name: "Datenschutz und IT-Sicherheit (MP)",
        status: "P",
        note: 1.0,
        credits: 5,
        datum: "15.08.2024",
        bewertung: "87/90",
      },
      {
        name: "Fallstudie Software-Engineering (MP)",
        status: "P",
        note: 1.3,
        credits: 5,
        datum: "–",
        bewertung: "91.3/100",
      },
      {
        name: "IT-Consulting & Dienstleistungsmanagement",
        status: "P",
        note: 1.7,
        credits: 5,
        datum: "30.09.2024",
        bewertung: "81/90",
      },
      {
        name: "Praxisprojekt IV",
        status: "P",
        note: 1.0,
        credits: 5,
        datum: "01.10.2024",
        bewertung: "97/100",
      },
      {
        name: "Qualitätssicherung im Softwareprozess (MP)",
        status: "P",
        note: 1.0,
        credits: 5,
        datum: "–",
        bewertung: "96.25/100",
      },
    ],
  },
  {
    name: "5. Semester",
    modules: [
      {
        name: "Data Analytics und Big Data (MP)",
        status: "P",
        note: 1.0,
        credits: 5,
        datum: "–",
        bewertung: "96/100",
      },
      {
        name: "Design Thinking",
        status: "P",
        note: 1.3,
        credits: 5,
        datum: "–",
        bewertung: "91/100",
      },
      {
        name: "Betriebssysteme, Rechnernetze & verteilte Systeme",
        status: "P",
        note: 1.7,
        credits: 5,
        datum: "11.02.2025",
        bewertung: "78/90",
      },
      {
        name: "Praxisprojekt V",
        status: "P",
        note: 1.3,
        credits: 5,
        datum: "01.04.2025",
        bewertung: "91/100",
      },
    ],
  },
  {
    name: "6. Semester",
    modules: [
      {
        name: "IT-Architekturmanagement",
        status: "P",
        note: 1.3,
        credits: 5,
        datum: "21.08.2025",
        bewertung: "93.33/100",
      },
      {
        name: "Planen und Entscheiden",
        status: "P",
        note: 1.3,
        credits: 5,
        datum: "31.07.2025",
        bewertung: "92/100",
      },
      {
        name: "Praxisprojekt VI",
        status: "E",
        note: null,
        credits: 5,
        datum: "29.09.2025",
        bewertung: "Bewertung folgt",
      },
    ],
  },
  {
    name: "7. Semester",
    modules: [
      { name: "E-Commerce", status: "CE", note: null, credits: 5, datum: "–" },
      {
        name: "Personal- und Unternehmensführung",
        status: "CE",
        note: null,
        credits: 5,
        datum: "–",
      },
      {
        name: "Unternehmensgründung & Innovationsmanagement",
        status: "CE",
        note: null,
        credits: 5,
        datum: "–",
      },
      {
        name: "Bachelorarbeit",
        status: "M",
        note: null,
        credits: 10,
        datum: "–",
      },
      {
        name: "Praxisberichte VII",
        status: "CE",
        note: null,
        credits: 5,
        datum: "–",
      },
    ],
  },
];

export const VERTIEFUNG_DATA_ANALYTICS: Section = {
  name: "Vertiefung: Data Analytics",
  modules: [
    {
      name: "Algorithmen, Datenstrukturen & Programmiersprachen I",
      status: "P",
      note: 1.7,
      credits: 5,
      datum: "19.08.2025",
    },
    { name: "… Fallstudie", status: "CE", note: null, credits: 5, datum: "–" },
    {
      name: "Business Intelligence I",
      status: "P",
      note: 1.3,
      credits: 5,
      datum: "–",
      bewertung: "92/100",
    },
    {
      name: "Business Intelligence II",
      status: "P",
      note: 1.0,
      credits: 5,
      datum: "01.08.2025",
      bewertung: "100/100",
    },
  ],
};

export const ZUSATZ_MODULE: Section = {
  name: "Zusatzmodule & Projekte",
  modules: [
    {
      name: "Projekt: KI-Exzellenz mit kreativen Prompt-Techniken",
      status: "P",
      note: 1.0,
      credits: 5,
      datum: "23.02.2025",
      bewertung: "100/100",
    },
    {
      name: "Artificial Intelligence (Wahlbereich)",
      status: "M",
      note: null,
      credits: 5,
      datum: "–",
    },
  ],
};

export const CHIP_CLASSES: Record<StatusKey, string> = {
  P: "bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 ring-1 ring-emerald-500/20",
  F: "bg-iu-red/10 text-iu-red ring-1 ring-iu-red/20",
  M: "bg-iu-orange/10 text-iu-orange ring-1 ring-iu-orange/20",
  CE: "bg-iu-blue/10 text-iu-blue ring-1 ring-iu-blue/20",
  E: "bg-iu-purple/10 text-iu-purple ring-1 ring-iu-purple/20",
};

export const CHIP_LABEL: Record<StatusKey, string> = {
  P: "Bestanden",
  F: "Nicht bestanden",
  M: "Offen",
  CE: "Angemeldet",
  E: "Zur Prüfung angemeldet",
};
