import type { Module } from "~/types/module-handbook";

export const userProfile = {
  name: "Demo Student",
  program: "B.Sc. Wirtschaftsinformatik",
  campus: "Campus Hamburg",
  cohort: "WiSe 23/24",
  focus: "Data & Process Management",
  advisor: "Dr. Johanna Kuester",
  advisorEmail: "studienberatung@campus-hamburg.example",
  pdfUrl: "/uploads/modulhandbuch-winfo.pdf",
  currentSemester: 7,
};

export const COURSE_META: Record<
  string,
  {
    ects: number;
    exam: string;
    semester: number;
    type: Module["type"];
    workload: number;
    skills?: string[];
    status?: Module["status"];
    description?: string;
  }
> = {
  "WI-101": {
    ects: 6,
    exam: "Klausur (120 Min)",
    semester: 1,
    type: "Pflicht",
    workload: 150,
    skills: ["Java", "Git", "Testing", "Clean Code"],
    description:
      "Grundlagen der Softwareentwicklung mit Fokus auf wartbare Architektur, Versionskontrolle und Testautomatisierung.",
    status: "laufend",
  },
  "WI-102": {
    ects: 5,
    exam: "Klausur (90 Min)",
    semester: 1,
    type: "Pflicht",
    workload: 125,
    skills: ["Wahrscheinlichkeit", "Hypothesentests", "Python"],
    description:
      "Mathematische Werkzeuge fuer datengetriebene Entscheidungen und erste Schritte in der explorativen Datenanalyse.",
    status: "laufend",
  },
  "WI-201": {
    ects: 6,
    exam: "Projekt + Fachgespraech",
    semester: 2,
    type: "Pflicht",
    workload: 150,
    skills: ["SQL", "Datenmodellierung", "Indexing", "APIs"],
    description:
      "Relationale Modellierung, Normalformen, Query-Optimierung und API-Anbindung mit praxisnahen Cases.",
    status: "geplant",
  },
  "WI-202": {
    ects: 5,
    exam: "Hausarbeit",
    semester: 2,
    type: "Pflicht",
    workload: 125,
    skills: ["COBIT", "ITIL", "Stakeholder-Management"],
    description:
      "Steuerung von IT-Landschaften, Service-Management und Risikobetrachtung fuer digitale Transformation.",
    status: "geplant",
  },
  "WI-301": {
    ects: 6,
    exam: "Case Study + Praesentation",
    semester: 3,
    type: "Wahl",
    workload: 150,
    skills: ["Power BI", "Process Mining", "Python"],
    description:
      "Analytische Auswertung von Prozessen, KPI-Design und Visualisierung datenbasierter Handlungsempfehlungen.",
    status: "geplant",
  },
  "WI-302": {
    ects: 6,
    exam: "Projekt (CI/CD Pipeline)",
    semester: 3,
    type: "Wahl",
    workload: 150,
    skills: ["Docker", "Kubernetes", "CI/CD"],
    description:
      "Deployment-Strategien, Observability und Automatisierung fuer skalierbare Anwendungen in der Cloud.",
    status: "geplant",
  },
  "WI-401": {
    ects: 6,
    exam: "Portfolio + Viva",
    semester: 4,
    type: "Wahl",
    workload: 150,
    skills: ["Regression", "Classification", "MLOps"],
    description:
      "Modellierung, Evaluierung und Operationalisierung von ML-Loesungen mit Fokus auf Business Impact.",
    status: "geplant",
  },
  "WI-402": {
    ects: 5,
    exam: "Praxisprojekt",
    semester: 4,
    type: "Wahl",
    workload: 125,
    skills: ["Product Discovery", "Roadmapping", "OKRs"],
    description:
      "Von der Idee zum digitalen Produkt: Nutzerzentrierte Entwicklung, Priorisierung und Go-to-Market-Plan.",
    status: "geplant",
  },
  "WI-501": {
    ects: 5,
    exam: "Hausarbeit + Praesentation",
    semester: 5,
    type: "Wahl",
    workload: 150,
    skills: ["Enterprise Architecture", "BPMN", "Stakeholder"],
    description:
      "Architektur- und Prozessgestaltung fuer skalierende Organisationen inkl. BPMN und EA-Patterns.",
    status: "geplant",
  },
  "WI-502": {
    ects: 5,
    exam: "Praesentation + Beratungsdossier",
    semester: 5,
    type: "Wahl",
    workload: 125,
    skills: ["Consulting", "Kommunikation", "Workshops"],
    description:
      "IT-Consulting mit Fokus auf Workshops, Storylining und Umsetzungsplaene fuer Stakeholder.",
    status: "geplant",
  },
  "WI-503": {
    ects: 5,
    exam: "Praesentation + Reflexion",
    semester: 5,
    type: "Pflicht",
    workload: 125,
    skills: ["Change", "Kommunikation", "Team"],
    description:
      "Change Management in IT-Projekten mit Fokus auf Kommunikation und Adoption.",
    status: "geplant",
  },
  "WI-504": {
    ects: 5,
    exam: "Portfolio",
    semester: 5,
    type: "Wahl",
    workload: 125,
    skills: ["Leadership", "Agilitaet", "Facilitation"],
    description:
      "Agile Leadership, Moderation und Servant Leadership fuer Tech Teams.",
    status: "geplant",
  },
  "WI-505": {
    ects: 5,
    exam: "Projektarbeit 5 + Praesentation",
    semester: 5,
    type: "Pflicht",
    workload: 150,
    skills: ["Projektarbeit", "Praxis", "Reporting"],
    description:
      "Projektarbeit 5 fuer duale Studierende mit Praxisanteil und Abschlusspruefung.",
    status: "geplant",
  },
  "WI-601": {
    ects: 5,
    exam: "Klausur (90 Min)",
    semester: 6,
    type: "Pflicht",
    workload: 150,
    skills: ["Security", "Compliance", "Risk"],
    description:
      "IT-Security, Datenschutz und Compliance mit Risikoanalyse und technischen Kontrollen.",
    status: "geplant",
  },
  "WI-602": {
    ects: 5,
    exam: "Hausarbeit",
    semester: 6,
    type: "Wahl",
    workload: 125,
    skills: ["Data Governance", "Ethics", "Policies"],
    description:
      "Datenqualitaet, Governance-Modelle und ethische Leitplanken fuer datengetriebene Produkte.",
    status: "geplant",
  },
  "WI-603": {
    ects: 5,
    exam: "Klausur (90 Min)",
    semester: 6,
    type: "Wahl",
    workload: 150,
    skills: ["Cloud", "Security", "Compliance"],
    description:
      "Cloud Security, Identity und Compliance Kontrollen in verteilten Systemen.",
    status: "geplant",
  },
  "WI-604": {
    ects: 5,
    exam: "Hausarbeit + Dashboard",
    semester: 6,
    type: "Wahl",
    workload: 125,
    skills: ["BI", "Datenmodellierung", "Reporting"],
    description:
      "Business Intelligence mit Datenmodellen, KPIs und Visualisierung.",
    status: "geplant",
  },
  "WI-605": {
    ects: 5,
    exam: "Projektarbeit 6 + Praesentation",
    semester: 6,
    type: "Pflicht",
    workload: 150,
    skills: ["Projektarbeit", "Praxis", "Stakeholder"],
    description:
      "Projektarbeit 6 fuer duale Studierende mit Abschlusspruefung.",
    status: "geplant",
  },
  "WI-701": {
    ects: 12,
    exam: "Bachelorarbeit + Kolloquium (60 Min)",
    semester: 7,
    type: "Pflicht",
    workload: 360,
    skills: ["Research", "Academic Writing", "Defense"],
    description:
      "Eigenstaendige wissenschaftliche Arbeit mit Kolloquium, Themenfokus Wirtschaftsinformatik.",
    status: "laufend",
  },
  "WI-702": {
    ects: 8,
    exam: "Projektbericht + Praesentation",
    semester: 7,
    type: "Pflicht",
    workload: 200,
    skills: ["Projektmanagement", "Praesentation", "Stakeholder"],
    description:
      "Praxisprojekt mit Unternehmensbezug, Abschluss durch schriftlichen Bericht und Praesentation.",
    status: "laufend",
  },
  "WI-703": {
    ects: 5,
    exam: "Praesentation (Team) + Reflexion",
    semester: 7,
    type: "Wahl",
    workload: 150,
    skills: ["Strategy", "Product", "Pitching"],
    description:
      "Strategische Entwicklung digitaler Produkte, Team-Pitch und persoenliche Reflexion.",
    status: "laufend",
  },
  "WI-704": {
    ects: 5,
    exam: "Praesentation + Reflexion",
    semester: 7,
    type: "Wahl",
    workload: 125,
    skills: ["Career", "Professional Skills"],
    description:
      "Career Lab mit Fokus auf Profil, Pitch und Bewerbungsunterlagen.",
    status: "laufend",
  },
  "WI-705": {
    ects: 5,
    exam: "Projektarbeit 7 + Praesentation",
    semester: 7,
    type: "Pflicht",
    workload: 150,
    skills: ["Projektarbeit", "Abschluss", "Praxis"],
    description: "Projektarbeit 7 fuer duale Studierende als Abschlussprojekt.",
    status: "laufend",
  },
  "WI-103": {
    ects: 5,
    exam: "Klausur (90 Min)",
    semester: 1,
    type: "Pflicht",
    workload: 125,
    skills: ["BWL", "Rechnung", "Organisation"],
    description:
      "Betriebswirtschaftliche Grundlagen fuer Wirtschaftsinformatiker.",
    status: "laufend",
  },
  "WI-104": {
    ects: 5,
    exam: "Portfolio + Praesentation",
    semester: 1,
    type: "Wahl",
    workload: 125,
    skills: ["Kommunikation", "Team", "Praesentation"],
    description: "Kommunikation und Teamarbeit mit Praesentationsuebungen.",
    status: "laufend",
  },
  "WI-105": {
    ects: 5,
    exam: "Projektarbeit 1 + Praesentation",
    semester: 1,
    type: "Pflicht",
    workload: 150,
    skills: ["Projektarbeit", "Praxis", "Dokumentation"],
    description: "Projektarbeit 1 fuer duale Studierende mit Praxisbezug.",
    status: "laufend",
  },
  "WI-203": {
    ects: 5,
    exam: "Hausarbeit",
    semester: 2,
    type: "Pflicht",
    workload: 125,
    skills: ["Requirements", "Dokumentation", "Methodik"],
    description: "Requirements Engineering und Spezifikationstechniken.",
    status: "geplant",
  },
  "WI-204": {
    ects: 5,
    exam: "Klausur (90 Min)",
    semester: 2,
    type: "Wahl",
    workload: 125,
    skills: ["Statistik", "Datenanalyse"],
    description: "Vertiefung Statistik mit Anwendungen in der Datenanalyse.",
    status: "geplant",
  },
  "WI-205": {
    ects: 5,
    exam: "Projektarbeit 2 + Praesentation",
    semester: 2,
    type: "Pflicht",
    workload: 150,
    skills: ["Projektarbeit", "Praxis", "Team"],
    description: "Projektarbeit 2 fuer duale Studierende.",
    status: "geplant",
  },
  "WI-303": {
    ects: 5,
    exam: "Klausur (90 Min)",
    semester: 3,
    type: "Wahl",
    workload: 125,
    skills: ["IT-Recht", "Compliance"],
    description: "IT-Recht, Datenschutz und Vertragsrecht im digitalen Umfeld.",
    status: "geplant",
  },
  "WI-304": {
    ects: 5,
    exam: "Projekt + Praesentation",
    semester: 3,
    type: "Wahl",
    workload: 125,
    skills: ["UX", "Design Thinking"],
    description: "UX und Design Thinking mit Prototyping.",
    status: "geplant",
  },
  "WI-305": {
    ects: 5,
    exam: "Projektarbeit 3 + Praesentation",
    semester: 3,
    type: "Pflicht",
    workload: 150,
    skills: ["Projektarbeit", "Praxis", "Stakeholder"],
    description: "Projektarbeit 3 fuer duale Studierende.",
    status: "geplant",
  },
  "WI-403": {
    ects: 5,
    exam: "Hausarbeit + Dashboard",
    semester: 4,
    type: "Wahl",
    workload: 125,
    skills: ["Data Warehousing", "ETL", "Modellierung"],
    description: "Data Warehousing, ETL Pipelines und Modellierung.",
    status: "geplant",
  },
  "WI-404": {
    ects: 5,
    exam: "Praesentation + Projektplan",
    semester: 4,
    type: "Pflicht",
    workload: 125,
    skills: ["Projektmanagement", "Planung"],
    description: "Projektmanagement mit Planung, Risiko und Steuerung.",
    status: "geplant",
  },
  "WI-405": {
    ects: 5,
    exam: "Projektarbeit 4 + Praesentation",
    semester: 4,
    type: "Pflicht",
    workload: 150,
    skills: ["Projektarbeit", "Praxis", "Reporting"],
    description: "Projektarbeit 4 fuer duale Studierende.",
    status: "geplant",
  },
};

export const RECOMMENDATIONS = [
  {
    code: "WI-301",
    title: "Data & Process Analytics",
    description: "Kombiniert BI, KPI-Design und Process Mining fuer datenbasierte Entscheidungen.",
  },
  {
    code: "WI-401",
    title: "Advanced Analytics & Machine Learning",
    description: "Vertieft Statistik und ML fuer automatisierte Vorhersagen inklusive MLOps-Blick.",
  },
  {
    code: "WI-302",
    title: "Cloud Architekturen & DevOps",
    description: "Damit deine Analytics-Use-Cases skalieren und automatisiert ausgerollt werden.",
  },
];
