export const TRANSLATIONS = {
  de: {
    title: "Einstellungen",
    subtitle: "Verwalte dein Konto, Benachrichtigungen und persönliche Präferenzen.",
    profile: "Profil",
    preferences: "Präferenzen",
    security: "Sicherheit",
    notifications: "Benachrichtigungen",
    logout: "Abmelden",
    profileInfo: "Profilinformationen",
    personalData: "Persönliche Daten",
    email: "E-Mail Adresse",
    phone: "Telefon",
    address: "Adresse",
    dateOfBirth: "Geburtsdatum",
    studentId: "Matrikelnummer",
    major: "Studiengang",
    company: "Unternehmen",
    supervisor: "Betreuer",
    changePassword: "Passwort ändern",
    currentPassword: "Aktuelles Passwort",
    newPassword: "Neues Passwort",
    confirmPassword: "Passwort bestätigen",
    changePasswordBtn: "Passwort aktualisieren",
    language: "Sprache",
    theme: "Design",
    darkMode: "Dunkler Modus",
    notificationSettings: "Benachrichtigungen",
    emailNotifications: "E-Mail-Benachrichtigungen",
    messageNotifications: "Nachrichten",
    calendarNotifications: "Kalender-Updates",
    enableAll: "Alle aktivieren",
    disableAll: "Alle deaktivieren",
    save: "Speichern",
    saved: "Gespeichert!",
    cancel: "Abbrechen",
    edit: "Bearbeiten",
    back: "Zurück zum Dashboard",
    twoFactor: "Zwei-Faktor-Authentifizierung",
    activeSession: "Aktive Sitzungen",
    loginHistory: "Anmeldungsverlauf",
    dataExport: "Datenexport",
    deleteAccount: "Konto löschen",
    accountDeletion: "Kontolöschung",
    deleteAccountWarning: "Dies kann nicht rückgängig gemacht werden",
    reminderTitle: "Praxisbericht-Erinnerung",
    reminderSubtitle: "Tägliche E-Mail-Erinnerung zur gewünschten Uhrzeit.",
    activate: "Aktivieren",
    time: "Uhrzeit",
    hour: "Uhr",
    saving: "Speichern...",
    controlCenter: "CONTROL CENTER",
    securelyStored: "Sicher gespeichert",
  },
  en: {
    title: "Settings",
    subtitle: "Manage your account, notifications, and personal preferences.",
    profile: "Profile",
    preferences: "Preferences",
    security: "Security",
    notifications: "Notifications",
    logout: "Logout",
    profileInfo: "Profile Information",
    personalData: "Personal Data",
    email: "Email Address",
    phone: "Phone",
    address: "Address",
    dateOfBirth: "Date of Birth",
    studentId: "Student ID",
    major: "Major",
    company: "Company",
    supervisor: "Supervisor",
    changePassword: "Change Password",
    currentPassword: "Current Password",
    newPassword: "New Password",
    confirmPassword: "Confirm Password",
    changePasswordBtn: "Update Password",
    language: "Language",
    theme: "Theme",
    darkMode: "Dark Mode",
    notificationSettings: "Notifications",
    emailNotifications: "Email Notifications",
    messageNotifications: "Messages",
    calendarNotifications: "Calendar Updates",
    enableAll: "Enable All",
    disableAll: "Disable All",
    save: "Save",
    saved: "Saved!",
    cancel: "Cancel",
    edit: "Edit",
    back: "Back to Dashboard",
    twoFactor: "Two-Factor Authentication",
    activeSession: "Active Sessions",
    loginHistory: "Login History",
    dataExport: "Data Export",
    deleteAccount: "Delete Account",
    accountDeletion: "Account Deletion",
    deleteAccountWarning: "This cannot be undone",
    reminderTitle: "Praxis Report Reminder",
    reminderSubtitle: "Daily email reminder at your preferred time.",
    activate: "Activate",
    time: "Time",
    hour: "h",
    saving: "Saving...",
    controlCenter: "CONTROL CENTER",
    securelyStored: "Securely stored",
  },
};

export const REMINDER_CACHE_KEY = "iu-reminder-preferences";
