export const TEXT = {
  de: {
    bulletin: "Campus Bulletin",
    title: "Abgaben",
    subtitle:
      "Verwalte deine Anträge, lade Dateien hoch und behalte Fristen im Blick – gestaltet wie eine sachliche Nachrichtenübersicht in hell und dunkel.",
    issue: "Ausgabe | Today",
    submissionsHeader: "Wissenschaftliche Arbeiten (Turnitin)",
    submitted: "Abgegeben",
    pending: "Ausstehend",
    dueDate: "Abgabefrist:",
    correction: "Korrektur:",
    daysLeft: (d: number) => (d > 0 ? `${d} Tage` : "Überfällig"),
    manageSubmission: "Abgabe verwalten",
    deadlineMissed: "Frist verpasst – keine Abgabe möglich",
    similarity: "Turnitin Ähnlichkeit:",
    examsHeader: "Klausurfristen",
    daysUntilExam: (d: number) =>
      d > 0 ? `${d} Tage` : d === 0 ? "Heute" : "Abgeschlossen",
    modalTitle: "Antrag ausfüllen",
    modalSubtitle: "Reiche deine Unterlagen sicher über unser Portal ein.",
    honor: "Ich bestätige die Richtigkeit der gemachten Angaben.",
    privacy: "Ich akzeptiere die Datenschutzbestimmungen für den Upload.",
    dropHere: "Datei hier ablegen oder klicken, um hochzuladen",
    orDrag: "oder Datei ablegen",
    chooseFile: "Datei auswählen",
    selected: "Ausgewählte Datei:",
    cancel: "Abbrechen",
    upload: "Einreichen",
    toastSuccess: "Dein Antrag wurde erfolgreich übermittelt!",
    alertAccept: "Bitte akzeptiere die Erklärungen und den Datenschutz.",
    alertUpload: "Bitte lade deine Datei hoch, bevor du fortfährst.",
    alertSelect: "Kein Antrag ausgewählt.",
  },
  en: {
    bulletin: "Campus Bulletin",
    title: "Submissions",
    subtitle:
      "Manage your applications, upload files, and track deadlines — styled like a clear news overview in light and dark.",
    issue: "Issue | Today",
    submissionsHeader: "Academic Papers (Turnitin)",
    submitted: "Submitted",
    pending: "Pending",
    dueDate: "Due date:",
    correction: "Correction:",
    daysLeft: (d: number) => (d > 0 ? `${d} days` : "Overdue"),
    manageSubmission: "Manage submission",
    deadlineMissed: "Deadline missed — no submission possible",
    similarity: "Turnitin similarity:",
    examsHeader: "Exam deadlines",
    daysUntilExam: (d: number) =>
      d > 0 ? `${d} days` : d === 0 ? "Today" : "Completed",
    modalTitle: "Fill Application",
    modalSubtitle: "Submit your documents securely via our portal.",
    honor: "I confirm the accuracy of the information provided.",
    privacy: "I accept the privacy policy for the upload.",
    dropHere: "Drop file here or click to upload",
    orDrag: "or drag & drop",
    chooseFile: "Choose file",
    selected: "Selected file:",
    cancel: "Cancel",
    upload: "Submit",
    toastSuccess: "Your application has been successfully submitted!",
    alertAccept: "Please accept the declarations and privacy notice.",
    alertUpload: "Please upload your file before continuing.",
    alertSelect: "No application selected.",
  },
};

export const WRITING_TYPES = [
  "Hausarbeit",
  "Seminararbeit",
  "Bachelorarbeit",
  "Masterarbeit",
  "Projektbericht",
  "Projektarbeit",
  "Workbook",
  "Fallstudie",
  "Portfolio",
  "Fachpräsentation",
];
